version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: CarService
      PGDATA: '/var/lib/pg_data'
    ports:
      - '5432:5432'
    networks:
      - local
volumes:
  pgdata:
    driver: local
networks:
  local:
