version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - /var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=CarService
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: CarService
      PGDATA: '/var/lib/pg_data'
    ports:
      - '5432:5432'
    networks:
      - local
volumes:
  pgdata:
    driver: local
networks:
  local:
